import { ArrowUpRight, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { Group } from '@/types'
import { Badge } from '@/components/ui/badge'
import { Card } from '@/components/ui/card'
import { MatchScore } from '@/components/recommendations/MatchScore'

interface GroupCardProps { group: Group; matchScore?: number; matchedInterests?: string[] }

export function GroupCard({ group, matchScore, matchedInterests }: GroupCardProps) { return <Card className="group overflow-hidden transition hover:-translate-y-1 hover:shadow-float"><div className="relative h-44 overflow-hidden"><Link to={`/groups/${group.id}`}><img src={group.imageUrl} alt={`${group.name} community`} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /></Link><span className="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1 text-xs font-extrabold">{group.category}</span>{matchScore !== undefined && <div className="absolute right-4 top-4 rounded-2xl bg-white/95 p-2 shadow"><MatchScore score={matchScore} compact /></div>}</div><div className="p-5"><div className="mb-3 flex items-start justify-between gap-3"><div><Link to={`/groups/${group.id}`}><h3 className="heading text-xl hover:text-coral">{group.name}</h3></Link><p className="mt-1 flex items-center gap-1 text-xs font-semibold text-ink/45"><Users size={13} /> {group.memberCount} members</p></div><Link to={`/groups/${group.id}`} aria-label={`Explore ${group.name}`} className="rounded-full bg-ink/5 p-2 transition hover:bg-sun"><ArrowUpRight size={16} /></Link></div><p className="line-clamp-2 text-sm leading-6 text-ink/60">{group.description}</p><div className="mt-4 flex flex-wrap gap-2">{(matchedInterests ?? group.tags).map((tag) => <Badge key={tag} className={matchedInterests ? 'bg-coral/10 text-coral' : ''}>{tag}</Badge>)}</div><Link to={`/groups/${group.id}`} className="mt-5 inline-flex items-center gap-2 text-sm font-extrabold text-coral">Explore community <ArrowUpRight size={15} /></Link></div></Card> }
