import { Link, NavLink, Outlet } from 'react-router-dom'
import { Bell, Plus, Sparkles } from 'lucide-react'
import { navigationItems } from '@/constants/navigation'
import { currentUser } from '@/data/mockData'
import { Avatar } from '@/components/ui/avatar'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'

function Logo() { return <Link to="/" className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-coral text-white"><Sparkles size={18} /></span><span className="font-display text-lg font-extrabold tracking-[-0.04em]">aatmoday<span className="text-coral">.</span></span></Link> }
export function AppLayout() { return <div className="min-h-screen bg-canvas"><aside className="fixed inset-y-0 left-0 z-20 hidden w-64 flex-col border-r border-line bg-surface px-5 py-7 lg:flex"><Logo /><nav className="mt-14 grid gap-2">{navigationItems.map(({ label, href, icon: Icon }) => <NavLink key={href} to={href} className={({ isActive }) => cn('flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-bold text-ink/50 transition hover:bg-ink/5 hover:text-ink', isActive && 'bg-ink text-white shadow-soft hover:bg-ink hover:text-white')}><Icon size={18} /> {label}</NavLink>)}</nav><div className="mt-auto rounded-2xl bg-mint/10 p-4"><p className="text-xs font-extrabold uppercase tracking-widest text-mint">New here?</p><p className="mt-2 text-sm font-bold leading-5">Complete your profile to unlock better matches.</p><Button variant="secondary" size="sm" className="mt-4 w-full">Add interests <Plus size={14} /></Button></div></aside><header className="sticky top-0 z-10 flex h-[72px] items-center justify-between border-b border-line bg-canvas/90 px-5 backdrop-blur lg:ml-64 lg:px-10"><div className="lg:hidden"><Logo /></div><div className="hidden text-sm font-semibold text-ink/45 lg:block">Tuesday, 12 November <span className="mx-2 text-line">/</span> Find your next thing</div><div className="flex items-center gap-3"><button aria-label="Notifications" className="rounded-full p-2 text-ink/50 hover:bg-ink/5"><Bell size={19} /></button><Link to="/profile" className="flex items-center gap-2"><Avatar src={currentUser.avatarUrl} alt={currentUser.name} size="sm" /><span className="hidden text-sm font-bold sm:block">{currentUser.name}</span></Link></div></header><main className="pb-24 lg:ml-64 lg:pb-10"><Outlet /></main><nav className="fixed inset-x-0 bottom-0 z-20 grid grid-cols-5 border-t border-line bg-surface/95 px-2 py-2 backdrop-blur lg:hidden">{navigationItems.map(({ label, href, icon: Icon }) => <NavLink key={href} to={href} className={({ isActive }) => cn('flex flex-col items-center gap-1 rounded-xl py-2 text-[10px] font-bold text-ink/45', isActive && 'bg-ink text-white')}><Icon size={18} /><span>{label}</span></NavLink>)}</nav></div> }
