import { ArrowLeft, CalendarDays, MapPin, Users } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { PageContainer } from '@/components/common/page-container'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Card } from '@/components/ui/card'
import { groups, events } from '@/data/mockData'

export function GroupDetailPage() { const { id } = useParams(); const group = groups.find((item) => item.id === id) ?? groups[0]; return <PageContainer><Link to="/groups" className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-ink/50 hover:text-ink"><ArrowLeft size={16} /> All communities</Link><div className="grid gap-8 lg:grid-cols-[1.35fr_1fr]"><div><img src={group.imageUrl} alt="" className="h-72 w-full rounded-2xl object-cover shadow-soft sm:h-96" /><div className="mt-7"><Badge className="bg-coral/10 text-coral">{group.category}</Badge><h1 className="heading mt-3 text-4xl sm:text-5xl">{group.name}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-ink/60">{group.description}</p><div className="mt-6 flex flex-wrap gap-2">{group.tags.map((tag) => <Badge key={tag}>{tag}</Badge>)}</div></div></div><Card className="h-fit p-6"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-mint/15 text-mint"><Users size={20} /></span><div><p className="heading text-xl">{group.memberCount} members</p><p className="text-xs font-semibold text-ink/45">A friendly place to start</p></div></div><Button className="mt-7 w-full" size="lg">Join community</Button><p className="mt-4 text-center text-xs font-semibold text-ink/40">{group.nextEvent}</p></Card></div></PageContainer> }

export function EventDetailPage() { const { id } = useParams(); const event = events.find((item) => item.id === id) ?? events[0]; return <PageContainer><Link to="/events" className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-ink/50 hover:text-ink"><ArrowLeft size={16} /> All events</Link><div className="grid gap-8 lg:grid-cols-[1.35fr_1fr]"><div><img src={event.imageUrl} alt="" className="h-72 w-full rounded-2xl object-cover shadow-soft sm:h-96" /><p className="mt-7 text-xs font-extrabold uppercase tracking-widest text-coral">{event.groupName}</p><h1 className="heading mt-3 text-4xl sm:text-5xl">{event.title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-ink/60">{event.description}</p></div><Card className="h-fit p-6"><div className="grid gap-5 text-sm font-bold"><span className="flex items-center gap-3"><CalendarDays className="text-coral" size={19} /> {event.date}, {event.time}</span><span className="flex items-center gap-3"><MapPin className="text-coral" size={19} /> {event.location}</span><span className="flex items-center gap-3"><Users className="text-coral" size={19} /> {event.attendees} people are going</span></div><Button className="mt-8 w-full" size="lg">I am interested</Button></Card></div></PageContainer> }
