import { ArrowRight, Search, Sparkles, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { PageContainer } from '@/components/common/page-container'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { groups, currentUser } from '@/data/mockData'
import { GroupCard } from '@/components/common/group-card'

export function HomePage() { return <PageContainer><motion.section initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="page-grid relative overflow-hidden rounded-[2rem] border border-line px-6 py-12 sm:px-12 lg:py-20"><div className="max-w-2xl"><p className="eyebrow mb-4 text-coral">A better way to find your people</p><h1 className="heading text-5xl leading-[1.05] sm:text-7xl">Your interests have a <span className="text-coral">community.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-ink/60 sm:text-lg">Tell us what you are into, and we will help you find the clubs, events, and kindred spirits waiting around campus.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/discover"><Button size="lg">Start discovering <ArrowRight size={18} /></Button></Link><Link to="/recommendations"><Button size="lg" variant="outline">See my matches <Sparkles size={18} /></Button></Link></div></div><div className="mt-12 grid max-w-xl grid-cols-3 gap-3 sm:absolute sm:bottom-10 sm:right-10 sm:mt-0 sm:w-80"><div className="rounded-2xl bg-coral p-4 text-white"><span className="heading text-3xl">42</span><p className="mt-1 text-xs font-bold opacity-80">active communities</p></div><div className="rounded-2xl bg-mint p-4 text-white"><span className="heading text-3xl">1.8k</span><p className="mt-1 text-xs font-bold opacity-80">students connected</p></div><div className="rounded-2xl bg-sun p-4 text-ink"><span className="heading text-3xl">∞</span><p className="mt-1 text-xs font-bold opacity-80">ways to belong</p></div></div></motion.section><section className="mt-14"><div className="mb-6 flex items-end justify-between"><div><p className="eyebrow mb-2">A little inspiration</p><h2 className="heading text-3xl">Popular right now</h2></div><Link to="/groups" className="hidden items-center gap-2 text-sm font-extrabold text-coral sm:flex">Explore all <ArrowRight size={16} /></Link></div><div className="grid gap-5 md:grid-cols-2">{groups.slice(0, 2).map((group) => <GroupCard key={group.id} group={group} />)}</div></section><section className="mt-12 flex flex-col items-center justify-between gap-5 rounded-2xl bg-ink p-6 text-white sm:flex-row sm:p-8"><div className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-xl bg-white/10"><Search size={22} /></span><div><p className="heading text-lg">What are you curious about?</p><p className="text-sm text-white/55">Build your interest profile in a few words.</p></div></div><Link to="/discover"><Button variant="secondary">Describe your interests <ArrowRight size={16} /></Button></Link></section></PageContainer> }
