import { Edit3, MapPin, Plus } from 'lucide-react'
import { PageContainer } from '@/components/common/page-container'
import { PageHeader } from '@/components/common/page-header'
import { Avatar } from '@/components/ui/avatar'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { currentUser } from '@/data/mockData'

export function ProfilePage() { return <PageContainer><PageHeader eyebrow="Your corner" title="A little more you" action={<Button variant="outline"><Edit3 size={16} /> Edit profile</Button>} /><div className="grid gap-6 lg:grid-cols-[280px_1fr]"><Card className="h-fit p-6 text-center"><Avatar src={currentUser.avatarUrl} alt={currentUser.name} size="lg" className="mx-auto" /><h2 className="heading mt-4 text-2xl">{currentUser.name}</h2><p className="mt-1 text-sm font-semibold text-coral">{currentUser.handle}</p><p className="mt-4 flex items-center justify-center gap-1 text-xs font-semibold text-ink/45"><MapPin size={13} /> {currentUser.course} · {currentUser.year}</p><p className="mt-5 text-sm leading-6 text-ink/60">{currentUser.bio}</p><div className="mt-6 border-t border-line pt-5"><p className="text-xs font-extrabold uppercase tracking-widest text-ink/40">Profile strength</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-ink/10"><div className="h-full w-[94%] rounded-full bg-mint" /></div><p className="mt-2 text-right text-xs font-bold text-mint">94%</p></div></Card><div><Card className="p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Your signals</p><h2 className="heading mt-1 text-2xl">Things I am into</h2></div><Button variant="ghost" size="sm"><Plus size={16} /> Add</Button></div><div className="mt-6 flex flex-wrap gap-2">{currentUser.interests.map((interest) => <Badge key={interest} className="bg-coral/10 px-4 py-2 text-coral">{interest}</Badge>)}</div></Card><Card className="mt-6 bg-sun/10 p-6"><p className="eyebrow text-coral">A note for future you</p><h2 className="heading mt-2 text-2xl">The best matches start with curiosity.</h2><p className="mt-3 max-w-lg text-sm leading-6 text-ink/60">Keep adding the things that make you lose track of time. We will keep looking for the right rooms to bring them into.</p></Card></div></div></PageContainer> }
