import { ArrowRight, Lightbulb, ThumbsDown, ThumbsUp } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageContainer } from '@/components/common/page-container'
import { PageHeader } from '@/components/common/page-header'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { useRecommendations } from '@/hooks/useApi'
import { LoadingState, ErrorState } from '@/components/common/states'

export function RecommendationsPage() { const query = useRecommendations(); return <PageContainer><PageHeader eyebrow="Curated for you" title="Your kind of people" detail="Based on your interests, your pace, and the things you might enjoy trying next." action={<Badge className="bg-mint/15 py-2 text-mint">94% profile complete</Badge>} />{query.isPending ? <LoadingState /> : query.isError ? <ErrorState onRetry={() => void query.refetch()} /> : <div className="grid gap-6 lg:grid-cols-2">{query.data?.map((recommendation) => <Card key={recommendation.id} className="overflow-hidden"><div className="relative h-48"><img src={recommendation.imageUrl} alt="" className="h-full w-full object-cover" /><div className="absolute right-4 top-4 rounded-full bg-white px-3 py-2 text-sm font-extrabold text-mint shadow">{recommendation.matchScore}% match</div></div><div className="p-6"><p className="text-xs font-extrabold uppercase tracking-widest text-coral">{recommendation.type === 'group' ? 'Community pick' : 'Event pick'}</p><h2 className="heading mt-2 text-2xl">{recommendation.title}</h2><p className="mt-1 text-sm text-ink/55">{recommendation.subtitle}</p><div className="mt-5 grid gap-3">{recommendation.reasons.map((reason) => <div key={reason.label} className="flex items-center justify-between rounded-xl bg-canvas px-4 py-3"><div><p className="text-xs font-extrabold">{reason.label}</p><p className="mt-1 text-xs text-ink/50">{reason.detail}</p></div><span className="text-sm font-extrabold text-mint">{reason.score}%</span></div>)}</div><div className="mt-5 rounded-xl border border-sun/40 bg-sun/10 p-4"><div className="flex gap-3"><Lightbulb className="shrink-0 text-coral" size={18} /><div><p className="text-xs font-extrabold uppercase tracking-widest text-coral">Try saying</p><p className="mt-2 text-sm font-bold leading-6">“{recommendation.icebreakers[0].text}”</p></div></div></div><div className="mt-5 flex items-center justify-between"><div className="flex gap-1"><Button variant="ghost" size="sm" aria-label="Not for me"><ThumbsDown size={16} /></Button><Button variant="ghost" size="sm" aria-label="Love this"><ThumbsUp size={16} /></Button></div><Link to={recommendation.type === 'group' ? `/groups/${recommendation.targetId}` : `/events/${recommendation.targetId}`}><Button size="sm">Take a look <ArrowRight size={15} /></Button></Link></div></div></Card>)}</div>}</PageContainer> }
