import { useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Bookmark, CalendarDays, Check, ChevronDown, Heart, MapPin, MessageCircle, RefreshCw, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { EmptyState } from '@/components/common/states'
import { PageContainer } from '@/components/common/page-container'
import { IcebreakerDialog } from '@/components/common/IcebreakerDialog'
import { MatchScore } from '@/components/recommendations/MatchScore'
import { RecommendationSkeleton } from '@/components/recommendations/RecommendationSkeleton'
import { findRecommendationContext, recommendationService } from '@/services/recommendationService'
import type { Event, Group, InterestProfile, Recommendation } from '@/types'

type FeedFilter = 'all' | 'communities' | 'events'
type FeedSort = 'recommended' | 'upcoming' | 'recent'

export function RecommendationsPage() {
  const recommendationsQuery = useQuery({ queryKey: ['recommendation-feed'], queryFn: recommendationService.list })
  const profileQuery = useQuery({ queryKey: ['recommendation-profile'], queryFn: recommendationService.getInterestProfile })
  const [filter, setFilter] = useState<FeedFilter>('all')
  const [sort, setSort] = useState<FeedSort>('recommended')
  const [savedIds, setSavedIds] = useState(() => recommendationService.getSavedIds())
  const [interestedIds, setInterestedIds] = useState(() => recommendationService.getInterestedIds())
  const visible = useMemo(() => [...(recommendationsQuery.data ?? [])].filter((item) => filter === 'all' || (filter === 'communities' && item.type === 'group') || (filter === 'events' && item.type === 'event')).sort((first, second) => sort === 'recommended' ? second.matchScore - first.matchScore : sort === 'upcoming' ? Number(second.type === 'event') - Number(first.type === 'event') : second.id.localeCompare(first.id)), [filter, recommendationsQuery.data, sort])
  const communities = visible.filter((item) => item.type === 'group')
  const events = visible.filter((item) => item.type === 'event')
  const loading = recommendationsQuery.isPending || profileQuery.isPending

  function toggleSaved(id: string) { const active = recommendationService.toggleSaved(id); setSavedIds((current) => active ? [...current, id] : current.filter((item) => item !== id)) }
  function toggleInterested(id: string) { const active = recommendationService.toggleInterested(id); setInterestedIds((current) => active ? [...current, id] : current.filter((item) => item !== id)) }

  return <PageContainer><div className="mx-auto max-w-7xl"><div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow mb-3 text-coral">Curated for your next chapter</p><h1 className="heading text-4xl sm:text-5xl">Your Aatmoday matches</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-ink/55 sm:text-base">Based on your interests, goals, and activities you're likely to enjoy.</p></div><Link to="/discover"><Button variant="outline">Edit interests</Button></Link></div>{loading ? <LoadingFeed /> : recommendationsQuery.isError || profileQuery.isError ? <ErrorPanel onRetry={() => { void recommendationsQuery.refetch(); void profileQuery.refetch() }} /> : profileQuery.data ? <><InterestProfile profile={profileQuery.data} /><FeedControls filter={filter} sort={sort} onFilterChange={setFilter} onSortChange={setSort} />{!visible.length ? <EmptyState title="Your next match is still taking shape" detail="Try adding another interest so we can find a better-fit community or event." /> : <><section className="mt-9"><SectionHeading title="Recommended Communities" detail="Groups that line up with the things you want to explore." />{communities.length ? <div className="grid gap-6 lg:grid-cols-2">{communities.slice(0, 2).map((item) => <CommunityCard key={item.id} recommendation={item} group={findRecommendationContext(item) as Group} saved={savedIds.includes(item.id)} interested={interestedIds.includes(item.id)} onSave={() => toggleSaved(item.id)} onInterested={() => toggleInterested(item.id)} />)}</div> : <EmptyState title="No communities in this view" detail="Switch to All to see community matches." />}</section><section className="mt-14"><SectionHeading title="Upcoming Events For You" detail="A few easy ways to turn a shared interest into a real plan." />{events.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{events.map((item) => <EventRecommendationCard key={item.id} recommendation={item} event={findRecommendationContext(item) as Event} saved={savedIds.includes(item.id)} interested={interestedIds.includes(item.id)} onSave={() => toggleSaved(item.id)} onInterested={() => toggleInterested(item.id)} />)}</div> : <EmptyState title="No events in this view" detail="Switch to All to see event matches." />}</section>{communities.slice(2).length > 0 && <section className="mt-14"><SectionHeading title="Explore More" detail="Good matches with a little more room to surprise you." /><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{communities.slice(2).map((item) => <CommunityCard key={item.id} recommendation={item} group={findRecommendationContext(item) as Group} saved={savedIds.includes(item.id)} interested={interestedIds.includes(item.id)} onSave={() => toggleSaved(item.id)} onInterested={() => toggleInterested(item.id)} compact />)}</div></section>}</>}</> : null}</div></PageContainer>
}

function InterestProfile({ profile }: { profile: InterestProfile }) { return <Card className="overflow-hidden border-ink bg-ink text-white shadow-float"><div className="grid gap-7 p-6 sm:p-8 lg:grid-cols-[0.75fr_1.25fr] lg:items-center"><div><p className="eyebrow text-white/50">Your interest profile</p><p className="mt-3 text-sm leading-6 text-white/60">{profile.explanation}</p></div><div className="grid gap-4 sm:grid-cols-2">{profile.signals.map((signal) => <div key={signal.id}><div className="mb-2 flex justify-between text-sm font-bold"><span>{signal.name}</span><span className="text-white/55">{signal.score}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className={`h-full rounded-full ${signal.color === 'coral' ? 'bg-coral' : signal.color === 'mint' ? 'bg-mint' : signal.color === 'sun' ? 'bg-sun' : 'bg-sky'}`} style={{ width: `${signal.score}%` }} /></div></div>)}</div></div></Card> }
function FeedControls({ filter, sort, onFilterChange, onSortChange }: { filter: FeedFilter; sort: FeedSort; onFilterChange: (value: FeedFilter) => void; onSortChange: (value: FeedSort) => void }) { return <div className="mt-10 flex flex-col justify-between gap-4 border-b border-line pb-4 sm:flex-row sm:items-center"><div className="flex gap-2">{([['all', 'All'], ['communities', 'Communities'], ['events', 'Events']] as const).map(([value, label]) => <button key={value} onClick={() => onFilterChange(value)} className={`rounded-full px-4 py-2 text-sm font-extrabold transition ${filter === value ? 'bg-ink text-white' : 'bg-ink/5 text-ink/50 hover:bg-ink/10'}`}>{label}</button>)}</div><label className="relative"><span className="sr-only">Sort recommendations</span><select value={sort} onChange={(event) => onSortChange(event.target.value as FeedSort)} className="h-10 appearance-none rounded-xl border border-line bg-surface px-3 pr-9 text-xs font-bold"><option value="recommended">Recommended</option><option value="upcoming">Upcoming</option><option value="recent">Recently Added</option></select><ChevronDown className="pointer-events-none absolute right-3 top-3 text-ink/45" size={14} /></label></div> }
function SectionHeading({ title, detail }: { title: string; detail: string }) { return <div className="mb-6"><h2 className="heading text-2xl sm:text-3xl">{title}</h2><p className="mt-2 text-sm text-ink/50">{detail}</p></div> }
function CommunityCard({ recommendation, group, saved, interested, onSave, onInterested, compact = false }: { recommendation: Recommendation; group: Group; saved: boolean; interested: boolean; onSave: () => void; onInterested: () => void; compact?: boolean }) { const [open, setOpen] = useState(false); return <Card className={`group overflow-hidden transition hover:-translate-y-1 hover:shadow-float ${compact ? 'md:flex md:gap-4 md:p-4' : ''}`}><div className={`relative ${compact ? 'md:h-28 md:w-28 md:shrink-0' : 'h-52'}`}><Link to={`/groups/${group.id}`}><img src={group.imageUrl} alt={`${group.name} community`} className="h-full w-full object-cover" /></Link><div className="absolute right-4 top-4 rounded-2xl bg-white/95 p-2 shadow"><MatchScore score={recommendation.matchScore} compact /></div></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-extrabold uppercase tracking-widest text-coral">{group.category}</p><Link to={`/groups/${group.id}`}><h3 className="heading mt-1 text-2xl hover:text-coral">{group.name}</h3></Link><p className="mt-1 flex items-center gap-1 text-xs font-semibold text-ink/45"><Users size={13} /> {group.memberCount} members</p></div><button onClick={onSave} aria-label="Save community" className={`rounded-full p-2 ${saved ? 'bg-sun' : 'bg-ink/5'}`}><Bookmark size={16} fill={saved ? 'currentColor' : 'none'} /></button></div><p className="mt-4 text-sm leading-6 text-ink/60">{group.description}</p><div className="mt-4 flex flex-wrap gap-2">{recommendation.matchedInterests.map((item) => <Badge key={item} className="bg-coral/10 text-coral">{item}</Badge>)}</div>{!compact && <WhyMatches recommendation={recommendation} />}<div className="mt-5 flex flex-wrap gap-2"><Link to={`/groups/${group.id}`} className="flex-1"><Button variant="outline" className="w-full">Explore</Button></Link><Button onClick={onInterested} className={`flex-1 ${interested ? 'bg-mint' : ''}`}>{interested ? <Check size={15} /> : <Heart size={15} />} {interested ? 'Interested' : "I'm Interested"}</Button></div><Button onClick={() => setOpen(true)} variant="ghost" className="mt-2 w-full"><MessageCircle size={16} /> Start a Conversation</Button></div><IcebreakerDialog open={open} onClose={() => setOpen(false)} interests={recommendation.matchedInterests} community={group.name} /></Card> }
function EventRecommendationCard({ recommendation, event, saved, interested, onSave, onInterested }: { recommendation: Recommendation; event: Event; saved: boolean; interested: boolean; onSave: () => void; onInterested: () => void }) { const [open, setOpen] = useState(false); return <Card className="group overflow-hidden transition hover:-translate-y-1 hover:shadow-float"><div className="relative h-44"><Link to={`/events/${event.id}`}><img src={event.imageUrl} alt={`${event.title} event`} className="h-full w-full object-cover" /></Link><div className="absolute right-3 top-3 rounded-2xl bg-white/95 p-2 shadow"><MatchScore score={recommendation.matchScore} compact /></div></div><div className="p-5"><div className="flex justify-between gap-3"><div><p className="text-xs font-bold text-coral">{event.groupName}</p><Link to={`/events/${event.id}`}><h3 className="heading mt-1 text-xl hover:text-coral">{event.title}</h3></Link></div><button onClick={onSave} aria-label="Save event" className={`rounded-full p-2 ${saved ? 'bg-sun' : 'bg-ink/5'}`}><Bookmark size={16} fill={saved ? 'currentColor' : 'none'} /></button></div><div className="mt-4 grid gap-2 text-xs font-semibold text-ink/55"><span className="flex items-center gap-2"><CalendarDays size={14} /> {event.date}, {event.time}</span><span className="flex items-center gap-2"><MapPin size={14} /> {event.location}</span></div><div className="mt-4 flex flex-wrap gap-2">{recommendation.matchedInterests.map((item) => <Badge key={item} className="bg-mint/10 text-mint">{item}</Badge>)}</div><Button onClick={onInterested} variant={interested ? 'secondary' : 'outline'} className="mt-5 w-full">{interested ? <Check size={15} /> : <Heart size={15} />} {interested ? 'Interested' : "I'm Interested"}</Button><Button onClick={() => setOpen(true)} variant="ghost" className="mt-2 w-full"><MessageCircle size={16} /> Start a Conversation</Button></div><IcebreakerDialog open={open} onClose={() => setOpen(false)} interests={recommendation.matchedInterests} community={event.groupName} event={event.title} /></Card> }
function WhyMatches({ recommendation }: { recommendation: Recommendation }) { return <div className="mt-5 rounded-xl bg-canvas p-4"><p className="mb-3 flex items-center gap-2 text-xs font-extrabold uppercase tracking-widest text-ink/45"><Check size={14} className="text-mint" /> Why this matches</p><div className="grid gap-2">{recommendation.reasons.map((reason) => <p key={reason.label} className="text-sm font-semibold text-ink/65">{reason.label}: <span className="font-medium text-ink/45">{reason.detail}</span></p>)}</div></div> }
function LoadingFeed() { return <><div className="mt-8 h-48 animate-pulse rounded-2xl bg-ink/5" /><div className="mt-10 grid gap-6 lg:grid-cols-2"><RecommendationSkeleton /><RecommendationSkeleton /></div></> }
function ErrorPanel({ onRetry }: { onRetry: () => void }) { return <Card className="mt-8 p-8 text-center"><RefreshCw className="mx-auto text-coral" /><h2 className="heading mt-4 text-2xl">Your matches need another moment.</h2><p className="mx-auto mt-2 max-w-md text-sm text-ink/55">We could not load the recommendation feed. Your interests are safe.</p><div className="mt-5 flex justify-center gap-3"><Button variant="outline" onClick={onRetry}>Try again</Button><Link to="/discover"><Button>Edit Interests</Button></Link></div></Card> }
